//
//  PDFBuilder.swift
//  LexIndia
//
//  Renders downloadable documents (court forms, exam notes, papers,
//  revision charts) into clean printable PDFs stored in the app's
//  Documents directory. Bare Acts are never passed through here.
//

import UIKit

enum PDFBuilder {
    private static let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
    private static let margin: CGFloat = 56

    static func fileURL(_ fileName: String) -> URL {
        FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent(fileName)
    }

    static func fileExists(_ fileName: String) -> Bool {
        FileManager.default.fileExists(atPath: fileURL(fileName).path)
    }

    static func deleteFile(_ fileName: String) {
        try? FileManager.default.removeItem(at: fileURL(fileName))
    }

    /// Renders the document and writes it to Documents. Returns the file URL.
    static func makePDF(title: String, subtitle: String, paragraphs: [String], fileName: String) -> URL? {
        let url = fileURL(fileName)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let contentWidth = pageRect.width - margin * 2

        var blocks: [(text: NSAttributedString, spacingAfter: CGFloat)] = []
        blocks.append((attributed("LEXINDIA · LEGAL REFERENCE", font: .systemFont(ofSize: 9, weight: .semibold), color: .darkGray, kern: 1.6), 14))
        blocks.append((attributed(title, font: .systemFont(ofSize: 21, weight: .bold), color: .black), 6))
        if !subtitle.isEmpty {
            blocks.append((attributed(subtitle, font: .systemFont(ofSize: 11), color: .darkGray), 18))
        }
        for paragraph in paragraphs {
            blocks.append((attributed(paragraph, font: .systemFont(ofSize: 11.5), color: .black, lineSpacing: 3.5), 11))
        }
        blocks.append((attributed("Generated by LexIndia · A legal reference, not legal advice.", font: .systemFont(ofSize: 8.5), color: .gray), 0))

        do {
            try renderer.writePDF(to: url) { context in
                context.beginPage()
                var y = margin
                for block in blocks {
                    let bounds = block.text.boundingRect(
                        with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                        options: [.usesLineFragmentOrigin, .usesFontLeading],
                        context: nil
                    )
                    let height = ceil(bounds.height)
                    if y + height > pageRect.height - margin {
                        context.beginPage()
                        y = margin
                    }
                    block.text.draw(
                        with: CGRect(x: margin, y: y, width: contentWidth, height: height),
                        options: [.usesLineFragmentOrigin, .usesFontLeading],
                        context: nil
                    )
                    y += height + block.spacingAfter
                }
            }
            return url
        } catch {
            print("[LexIndia] PDF generation failed: \(error.localizedDescription)")
            return nil
        }
    }

    private static func attributed(
        _ text: String,
        font: UIFont,
        color: UIColor,
        kern: CGFloat = 0,
        lineSpacing: CGFloat = 0
    ) -> NSAttributedString {
        let style = NSMutableParagraphStyle()
        style.lineSpacing = lineSpacing
        return NSAttributedString(string: text, attributes: [
            .font: font,
            .foregroundColor: color,
            .kern: kern,
            .paragraphStyle: style
        ])
    }
}
