//
//  LexStrings.swift
//  LexIndia
//
//  Central interface-string table keyed by AppLanguage. Covers navigation,
//  hubs, search, documents, Students Corner, quizzes, E-Vakeel, settings
//  and common actions. Add a language case + table and every screen picks
//  it up. Official statutory text is NEVER translated here — it always
//  stays as enacted.
//

import Foundation

nonisolated enum LexStrings {
    /// Resolves a key for the given language, falling back to English.
    static func t(_ key: String, _ language: AppLanguage) -> String {
        if language != .english, let value = tables[language]?[key] {
            return value
        }
        return english[key] ?? key
    }

    private static let english: [String: String] = [
        // Tabs
        "tab.myspace": "My Space",
        "tab.library": "Law Library",
        "tab.students": "Students Corner",
        "tab.account": "Account",

        // Greetings
        "greeting.morning": "Good morning",
        "greeting.afternoon": "Good afternoon",
        "greeting.evening": "Good evening",

        // Common
        "common.seeAll": "See all",
        "common.clear": "Clear",
        "common.cancel": "Cancel",
        "common.save": "Save",
        "common.close": "Close",
        "common.done": "Done",
        "common.comingSoon": "Coming soon",
        "common.open": "Open",
        "trust.footnote": "LexIndia is a legal reference, not legal advice.",
        "prepared.title": "In preparation",
        "guide.badge": "Guide",

        // My Space
        "myspace.tagline": "Your reading, saves, notes and downloads.",
        "myspace.searchPlaceholder": "Search all of LexIndia…",
        "myspace.membership": "Membership",
        "myspace.quiz.title": "Quiz Challenge",
        "myspace.quiz.available": "Weekly reward available",
        "myspace.quiz.claimed": "Play in Students Corner",
        "myspace.studyTools": "Study tools",
        "myspace.categories": "Legal categories",
        "myspace.categories.sub": "Browse the law by area",
        "myspace.browseCodes": "Browse the codes",
        "myspace.allLaws": "All laws",
        "myspace.continueReading": "Continue where you left off",
        "myspace.startClassic": "Start with a classic",
        "myspace.situations": "What are you dealing with?",
        "myspace.topics": "Relevant topics",
        "myspace.recents": "Recently viewed",
        "myspace.saved": "Saved & notes",
        "myspace.downloads": "My downloads",
        "myspace.trial": "Free trial",
        "myspace.trial.endsIn": "Ends in",
        "myspace.seePlans": "See plans",
        "myspace.hint.saved": "Bookmark sections while reading — they'll live here with your notes.",
        "myspace.hint.downloads": "Court forms, exam notes and papers can be downloaded from Documents.",

        // Library
        "library.title": "Law Library",
        "library.subtitle": "Laws, study material, updates and documents",
        "library.lawsActs": "Laws & Acts",
        "library.study": "Study material",
        "library.updates": "Legal Updates",
        "library.allUpdates": "All updates",
        "library.documents": "Documents",
        "library.documentsForms": "Documents & forms",
        "library.documents.sub": "Bare Acts · Court forms · Study PDFs",
        "library.documents.foot": "Bare Acts read in app · forms download & print",
        "library.browseArea": "Browse by area",
        "library.topics": "Popular topics",
        "library.ipc.sub": "Find where an old IPC section lives in the new code",
        "library.student.title": "Students Corner",
        "library.student.sub": "Exam notes · Previous year papers · Revision",
        "library.student.foot": "Download and print for your preparation",

        // Students Corner
        "students.title": "Students Corner",
        "students.subtitle": "Quizzes, notes, papers and tools for law students",
        "students.quizzes": "Quizzes",
        "students.quiz.sub": "Test yourself · earn weekly credits",
        "students.quiz.cta": "Set up a quiz",
        "students.resources": "Study resources",
        "students.tools": "Study tools",
        "students.coming": "Coming to Students Corner",
        "students.courses": "Courses",
        "students.courses.sub": "Structured learning paths",
        "students.competitions": "Competitions",
        "students.competitions.sub": "Essay and quiz contests",
        "students.moot": "Online Moot Courts",
        "students.moot.sub": "Practice advocacy from your phone",

        // Quiz
        "quiz.title": "Quiz Challenge",
        "quiz.subtitle": "Pick your topics, choose the length, start",
        "quiz.topics": "Topics",
        "quiz.topics.hint": "Select one or more",
        "quiz.length": "Number of questions",
        "quiz.available": "available with this selection",
        "quiz.start": "Start quiz",
        "quiz.needTopics": "Select at least one topic to begin.",
        "quiz.pool.short": "Not enough questions for this length — add another topic.",
        "quiz.weekly.available": "Weekly reward available",
        "quiz.weekly.claimed": "Weekly reward claimed — resets next week",
        "quiz.weekly.rule": "Score 100% in five quizzes in a row to unlock the weekly credit reward. Claimable once a week — quizzes stay playable anytime.",
        "quiz.reward.per": "credits",
        "quiz.question": "Question",
        "quiz.result.title": "Your result",
        "quiz.result.pass": "Excellent work!",
        "quiz.result.fail": "Keep practising",
        "quiz.result.rewardAdded": "credits added to your balance",
        "quiz.streak.title": "Quiz Streak",
        "quiz.streak.progress": "%d / %d perfect scores",
        "quiz.streak.one": "One more 100% quiz to unlock your weekly reward.",
        "quiz.streak.need": "%d more 100% quizzes to unlock your weekly reward.",
        "quiz.streak.reset": "A score below 100% restarts the streak — keep practising!",
        "quiz.streak.ready": "Streak complete — finish your next quiz to receive the reward.",
        "quiz.streak.complete": "Streak complete! Your reward unlocks with next week's first quiz.",
        "quiz.streak.afterClaim": "Reward claimed — a new streak begins now.",
        "quiz.streak.chip": "Streak %d/%d",
        "quiz.result.timeUp": "Time ran out — your quiz was submitted automatically.",
        "quiz.time.used": "Time used",
        "quiz.time.left": "Time left",
        "quiz.result.correct": "Correct",
        "quiz.result.incorrect": "Incorrect",
        "quiz.result.unanswered": "Unanswered",
        "quiz.result.questions": "Questions",
        "quiz.result.perfect": "Perfect score!",
        "quiz.review.title": "Question review",
        "quiz.review.sub": "Every question with your answer and the correct one.",
        "quiz.review.your": "Your answer",
        "quiz.review.correct": "Correct answer",
        "quiz.review.notAnswered": "Not answered",
        "quiz.playAgain": "Play again",
        "quiz.exit.title": "Leave the quiz?",
        "quiz.exit.message": "Your progress in this quiz will be lost.",
        "quiz.exit.confirm": "Leave",

        // E-Vakeel
        "evakeel.name": "E-Vakeel",
        "evakeel.tagline": "Your digital legal assistant",
        "evakeel.placeholder": "Ask about a law, process or term…",
        "evakeel.disclaimer": "E-Vakeel gives general legal information — it is not a replacement for a qualified advocate.",
        "evakeel.empty.title": "Namaste 🙏",
        "evakeel.empty.message": "Ask what a law means, what a process involves, or what steps you can consider.",
        "evakeel.try": "Try asking",
        "evakeel.thinking": "E-Vakeel is thinking…",
        "evakeel.outOfCredits": "You're out of credits. The library, search and your notes stay fully available.",
        "evakeel.needMore": "This question needs more credits than you have right now.",
        "evakeel.manage": "Manage credits in Account",
        "evakeel.advocate": "For a matter like this, please consider consulting a qualified advocate — E-Vakeel is not a replacement for one.",
        "evakeel.clear": "Clear conversation",
        "evakeel.creditUsed": "credit used",
        "evakeel.creditsUsed": "credits used",
        "evakeel.noCharge": "No credit was used for this question.",
        "evakeel.provision": "Relevant provision",
        "evakeel.openSection": "Open section",

        // Search
        "search.title": "Search LexIndia",
        "search.placeholder": "Search the whole of LexIndia…",
        "search.recent": "Recent",
        "search.popular": "Popular searches",
        "search.noResults": "No results found",
        "search.noResults.sub": "Try a section number, legal term, Act, document or setting.",
        "search.hint": "Search everything — laws, sections, IPC numbers, terms, cases, documents, notes, updates and settings.",
        "search.group.library": "Law Library",
        "search.group.ipc": "IPC → BNS",
        "search.group.terms": "Legal terms",
        "search.group.cases": "Case laws",
        "search.group.documents": "Documents",
        "search.group.students": "Students Corner",
        "search.group.updates": "Legal Updates",
        "search.group.myspace": "My Space",
        "search.group.settings": "Settings",
        "search.linkedSections": "linked sections",

        // Account
        "account.title": "Account",
        "account.credits": "Credits",
        "account.credits.balance": "E-Vakeel credits",
        "account.credits.left": "left",
        "account.credits.history": "Credit history",
        "account.credits.note": "Your credit balance is visible only here.",
        "account.yourLibrary": "Your library",
        "account.studyTools": "Study tools",
        "account.settings": "Settings",
        "account.about": "About",
        "account.session": "Session",
        "account.saved": "Saved & notes",
        "account.recents": "Recently viewed",
        "account.downloads": "My downloads",
        "account.definitions": "Definitions",
        "account.caseLaws": "Case laws",
        "account.appearance": "Appearance",
        "account.language": "Language",
        "account.appColor": "App colour",
        "account.privacy": "Privacy",
        "account.terms": "Terms of use",
        "account.disclaimer": "Legal disclaimer",
        "account.signout": "Sign out",
        "account.membership": "Membership",

        // Theme modes
        "theme.system": "Automatic",
        "theme.system.detail": "Match your iPhone appearance",
        "theme.light": "Light",
        "theme.light.detail": "Bright canvas, deep bold ink",
        "theme.dark": "Dark",
        "theme.dark.detail": "Deep purple canvas, light ink",
        "appearance.title": "Appearance",
        "appearance.sub": "Light, dark, or match your iPhone",

        // App colour
        "appcolor.title": "App colour",
        "appcolor.sub": "Pick one colour — LexIndia matches the rest",
        "appcolor.presets": "LexIndia palettes",
        "appcolor.custom": "Custom colour",
        "appcolor.custom.pick": "Pick any colour from the wheel",
        "appcolor.preview": "Preview",
        "appcolor.reset": "Reset to LexIndia Violet",
        "appcolor.note": "Pick any colour and the whole app re-tints in shades of it — tiles, icons and badges included. Backgrounds stay light or dark as per your theme. LexIndia Violet keeps the signature colourful mix.",

        // Language screen
        "language.title": "Language",
        "language.sub": "Choose your LexIndia interface language",
        "language.how": "How language works",
        "language.body1": "Your choice applies across the LexIndia interface — navigation, buttons, settings, search, students corner and messages — and keeps growing.",
        "language.body2": "Official statutory text always remains exactly as enacted — it never changes with your interface language.",
        "language.more": "More Indian languages are on the way.",

        // Documents
        "docs.title": "Documents",
        "docs.sub": "Organised by what you need them for",
        "docs.readInApp": "Read in LexIndia",
        "docs.downloadPdf": "Download PDF",
        "docs.openPdf": "Open PDF",
        "docs.share": "Share",
        "docs.print": "Print",
        "docs.remove": "Remove",
        "docs.saved": "Saved to your device",
        "docs.links": "Important links",
        "docs.links.sub": "Official portals — open in your browser",
        "docs.policy.bareActs": "Bare Acts — read in app",
        "docs.policy.forms": "Forms & notes — PDF",
        "docs.readHere": "Read it here",

        // Reader & content
        "reader.section": "Section",
        "reader.official": "Official text",
        "reader.simple": "In simple words",
        "reader.understand": "Understand more",
        "reader.cases": "Landmark cases",

        // Read aloud + translate
        "readaloud.listen": "Listen",
        "readaloud.stop": "Stop reading",
        "translate.action": "Translate to Hindi",

        // Updates
        "updates.title": "Legal Updates",
        "updates.sub": "Courts, new laws, amendments and notifications",
        "updates.cat.supreme-court": "Supreme Court",
        "updates.cat.high-court": "High Courts",
        "updates.cat.judgment": "Judgments",
        "updates.cat.new-law": "New laws",
        "updates.cat.amendment": "Amendments",
        "updates.cat.notification": "Notifications",
        "updates.preview": "Preview content. LexIndia will publish original editorial summaries here — sourced, reviewed, then published. Demo entries show how it will read.",
        "updates.read": "Read summary",
        "updates.demo.note": "This is a demo summary shown while Legal Updates is in preview. Production updates will be original LexIndia summaries prepared through an editorial review, based on official sources or properly licensed content.",

        // Document kinds & detail
        "docs.kind.bare-act": "Bare Acts",
        "docs.kind.bare-act.blurb": "Official texts — read inside LexIndia",
        "docs.kind.court-form": "Court forms",
        "docs.kind.court-form.blurb": "Practical formats — download and print",
        "docs.kind.exam-note": "Exam notes",
        "docs.kind.exam-note.blurb": "LexIndia notes for exam preparation",
        "docs.kind.previous-paper": "Previous year papers",
        "docs.kind.previous-paper.blurb": "Practice papers for self-testing",
        "docs.kind.revision": "Revision material",
        "docs.kind.revision.blurb": "Compact charts for a final read",
        "docs.badge.readInApp": "Read in app",
        "docs.badge.downloaded": "Downloaded",
        "docs.bareact.note": "Official Bare Acts are part of the LexIndia library and open inside the app — with guides, IPC references and cases attached. They are not downloadable to your device.",
        "docs.download.note": "Saves a printable PDF to your device — open, share or print it anytime from My Downloads, even offline.",
        "docs.downloadedLine": "Downloaded %@ · in My Downloads",
        "docs.link.indiacode": "Official repository of Central and State Acts",
        "docs.link.ecourts": "Case status, cause lists and court orders",
        "docs.link.sci": "Judgments, cause lists and display board",
        "docs.link.efiling": "File cases online in District Courts and High Courts",

        // Library act tiles
        "library.badge.fulltext": "Full text",
        "library.badge.ipcmap": "IPC map",
        "library.badge.guided": "guided",
        "library.badge.sections": "sections",
        "prepared.badge": "Preparing",
        "prepared.message": "The full text of this Act is being prepared for LexIndia. Fully guided sections are available in other Acts of the Library.",

        // Act detail
        "act.contents": "Contents",
        "act.searchIn": "Search within this Act",
        "act.ipcCard.title": "Coming from the IPC?",
        "act.ipcCard.sub": "Convert an old IPC number to its BNS provision",
        "act.beingPrepared": "Being prepared",
        "act.source": "Source",
        "act.notFound.title": "Not available",
        "act.notFound.act": "This Act could not be found.",
        "act.notFound.category": "This category could not be found.",
        "act.noMatches": "No matches",
        "act.noMatches.sub": "Try a section number or a word from its title.",
        "act.guidedSections": "guided sections",
        "chapter.foot.some": "%d sections · plain-language guides for %d so far.",
        "chapter.foot.none": "%d sections · plain-language guides are being prepared.",
        "chapter.notFound": "This chapter could not be found.",

        // Reader extras
        "reader.chapter": "Chapter",
        "reader.swipe": "Swipe between sections",
        "reader.sAbbrev": "S.",
        "understand.example": "Example",
        "understand.keypoints": "Key points",
        "understand.related": "Related",
        "understand.definitions": "Definitions",
        "understand.earlier": "Earlier",
        "understand.oldcode": "Old code reference",
        "understand.relatedSections": "Related sections",
        "understand.casesOne": "1 case for this section",
        "understand.casesMany": "%d cases for this section",

        // My Space tools & membership
        "myspace.tool.defs": "Legal terms, explained",
        "myspace.tool.cases": "Landmark judgments",
        "myspace.tool.ipc": "Old code to new",
        "myspace.tool.study": "Notes · papers · revision",
        "myspace.until": "Until %@",
        "account.noPlan": "No plan",
        "account.devOnly": "Development only",
        "account.testAccess": "Test access",
        "plan.suffix": "plan",

        // Study material
        "study.sub": "Made for law students — download, print, revise",
        "study.note": "More material is added regularly. Papers marked “demo” are LexIndia practice sets, not actual past papers.",

        // Definitions
        "defs.sub": "Understand legal terms in plain language",

        // IPC converter
        "ipc.note": "Mappings reflect the correspondence tables for the 2023 codes. Where a provision was reworked, the note says so — equivalence is not claimed.",
        "ipc.open": "Open BNS section",
        "ipc.preparing": "Guide being prepared",
        "ipc.emptyTitle": "No mapping found",
        "ipc.emptySub": "Try an IPC number like 420, 302 or 498A.",
        "ipc.all": "All mappings · IPC order",
        "ipc.search": "Search an IPC section, e.g. 420",
        "ipc.matches": "matches",
        "defs.emptyTitle": "No matching terms",
        "defs.emptySub": "Try a different word — or browse the full glossary.",

        // Situations
        "situation.note": "These provisions help you discover relevant legal information. They are not personalised legal advice.",
        "situation.provisions": "Provisions in LexIndia related to this topic",
        "situation.relevant": "Relevant provisions",
        "situation.terms": "Terms to know",
        "situation.notFound": "This situation guide could not be found.",
        "topic.notFound": "This topic could not be found.",
        "defs.search": "Search terms",
        "defs.one": "Definition",

        // Case laws
        "cases.sub": "Judgments that shaped how the law is read",
        "cases.note": "Case information is provided as reference. Always verify against the official judgment.",
        "cases.search": "Search case laws",
        "cases.emptyTitle": "No matching cases",
        "cases.emptySub": "Try a party name or a word from the principle.",
        "cases.one": "Case law",
        "cases.principle": "Key principle",
        "cases.summary": "Summary",
        "cases.related": "Related provisions",
        "cases.notFound": "This case could not be found.",

        // Quiz topics
        "quiz.topic.bns": "Criminal Law — BNS",
        "quiz.topic.ipcBns": "IPC → BNS",
        "quiz.topic.bnss": "Procedure — BNSS",
        "quiz.topic.evidence": "Evidence — BSA",
        "quiz.topic.constitution": "Constitutional Law",
        "quiz.topic.contract": "Contract Act",
        "quiz.topic.definitions": "Legal terms",
        "quiz.topic.cases": "Landmark cases",

        // Credits
        "credits.explainer": "Simple questions use 1 credit; detailed ones use more. Weekly quiz rewards add free credits.",
        "credits.low": "Running low — top up to keep asking without interruption.",
        "credits.demo": "Demo purchase — no payment is charged in this preview build.",
        "credits.becomes": "Your balance becomes %d credits. No payment is charged in this preview.",
        "credits.out": "You're out of credits. The library, search and your notes remain fully available — add credits to keep asking E-Vakeel.",
        "credits.summary": "Balance %d · used %d · added %d",

        // Credits screens
        "credits.buyMore": "Buy more credits",
        "credits.recent": "Recent activity",
        "credits.demoTitle": "Demo purchase",
        "credits.addPack": "Add %d credits — %@",
        "credits.remaining": "Remaining",
        "credits.used": "Used",
        "credits.added": "Added",
        "credits.pack.popular": "Popular",
        "credits.pack.best": "Best value",
        "credits.emptyTitle": "No activity yet",
        "credits.emptySub": "Credit purchases, E-Vakeel usage and quiz rewards will appear here.",

        // Notes & downloads
        "notes.add": "Add a note…",
        "notes.savedOn": "Saved %@",
        "notes.emptyTitle": "No saved notes yet",
        "notes.emptySub": "Save sections while reading and they'll appear here.",
        "notes.search": "Search your notes",
        "notes.your": "Your note",
        "notes.saveNote": "Save note",
        "common.delete": "Delete",
        "downloads.browse": "Browse documents",
        "downloads.emptyTitle": "No downloads yet",
        "downloads.emptySub": "Court forms, exam notes, papers and revision charts can be saved to your device as printable PDFs.",
        "recents.emptySub": "Sections you read will appear here so you can pick up where you left off.",

        // Account extras
        "account.name.note": "Shown in your My Space greeting.",
        "account.local.note": "Your notes, saved sections and membership stay on this device.",
        "account.expiresLine": "Expires %@ · %d E-Vakeel credits included",
        "account.trial.line": "Full access · ends in %@",
        "account.dev.note": "Permanent development access — not a real plan. Removed before release.",
        "account.plus.note": "The full legal library, plain-language explanations, study tools and E-Vakeel credits.",

        // Appearance body
        "appearance.body1": "Automatic follows your iPhone's light and dark setting, so LexIndia always feels at home. Choose Light or Dark to keep one look at all times.",
        "appearance.body2": "In both looks, text and colors keep strong contrast — deep bold ink on the light canvas, light ink on the dark one.",
        "appcolor.family": "Your colour family",
        "appearance.how": "How appearance works",

        // Common extras
        "common.notNow": "Not now",
        "common.name": "Name",
        "account.yourName": "Your name",
        "account.signoutTitle": "Sign out?",
        "account.managePlan": "Manage plan",
        "common.all": "All",
        "updates.empty": "Nothing here yet",
        "updates.empty.sub": "Updates in this category will appear as they are published.",
        "updates.provisions": "Read the provisions",
        "updates.previewShort": "Preview content",
        "updates.notFound": "This update could not be found.",
        "docs.notFound": "This document could not be found.",

        // Paywall
        "paywall.demo": "Demo checkout — no payment is charged in this preview build.",
        "paywall.includes": "Includes %d E-Vakeel credits. No payment is charged in this preview.",
        "paywall.hero": "All of Indian law,\nmade simple.",
        "paywall.feature1": "Every guided Act, chapter and section",
        "paywall.feature2": "Official text with plain-language explanations",
        "paywall.feature3": "IPC → BNS map, search, quizzes and E-Vakeel",
        "paywall.try": "Try free for 24 hours",
        "paywall.try.sub": "Full access · no payment · we'll remind you before it ends",
        "paywall.dev.note": "Permanent test access for exploring the app without the 24-hour limit. Not a real plan — this option is disabled and removed before production.",
        "paywall.dev.cta": "Unlock permanent test access",
        "paywall.signedIn": "Signed in as %@",
        "paywall.best": "BEST VALUE",
        "paywall.save": "Save ₹%d",
        "paywall.planLine": "%@ · %d E-Vakeel credits",
        "paywall.start": "Start %@ — %@",

        // Subscription sheet
        "sub.membership": "Membership",
        "sub.title": "LexIndia Plus",
        "sub.tagline": "The complete legal reference — read, understand and study Indian law without limits.",
        "sub.trial.active": "Free trial active",
        "sub.trial.endsLine": "Ends in %@. Pick a plan to keep everything.",
        "sub.dev.active": "Permanent test access is active. Subscribing below replaces it with a real plan.",
        "sub.dev.end": "End test access",
        "sub.dev.endTitle": "End test access?",
        "sub.dev.endMessage": "You'll return to the subscription screen.",
        "sub.dev.keep": "Keep it",
        "sub.planActive": "%@ plan active",
        "sub.planLine": "%@ · included %d E-Vakeel credits",
        "sub.started": "Started",
        "sub.expires": "Expires",
        "sub.balance": "E-Vakeel credit balance",
        "sub.included": "Included",
        "sub.feat1": "Full legal library — every guided Act and section",
        "sub.feat2": "Plain-language explanations and real-life examples",
        "sub.feat3": "Search, definitions, landmark cases and IPC → BNS",
        "sub.feat4": "Notes and saved sections",
        "sub.feat5": "E-Vakeel credits included with every plan",
        "sub.cancel": "Cancel subscription",
        "sub.cancelTitle": "Cancel subscription?",
        "sub.cancelMessage": "Demo cancellation — access ends immediately in this preview.",
        "sub.keepPlan": "Keep my plan",

        // Auth
        "auth.tagline": "Indian law, in simple words. Read the sections, understand them, and study with confidence.",
        "auth.preview.note": "Preview sign-in — your account is stored on this device. Production authentication arrives with the backend.",
        "auth.register": "Create account",
        "auth.signin": "Sign in",
        "auth.toggle.toSignin": "Already have an account? **Sign in**",
        "auth.toggle.toRegister": "New to LexIndia? **Create an account**",
        "auth.email": "Email address",
        "auth.err.email": "Please enter a valid email address.",
        "auth.err.name": "Please enter your name.",
        "auth.err.notFound": "No account with this email was found on this device. Create one instead.",

        // Trial & paywall extras
        "trial.keep": "Keep every section, explanation and study tool.",
        "trial.endsLine": "Your free day ends in %@. Plans start at ₹128.",
        "paywall.choose": "Choose your plan",
        "paywall.demoTitle": "Demo checkout",
        "sub.plans": "Plans",
        "paywall.continue": "Continue — %@ · %@",
        "paywall.expired.trial": "Your free day has ended. Pick a plan to keep reading — everything you saved is waiting.",
        "paywall.expired.plan": "Your plan has ended. Renew to keep reading — everything you saved is waiting."
    ]

    private static let tables: [AppLanguage: [String: String]] = [
        .hindi: [
            // Tabs
            "tab.myspace": "मेरा स्पेस",
            "tab.library": "लॉ लाइब्रेरी",
            "tab.students": "स्टूडेंट्स कॉर्नर",
            "tab.account": "अकाउंट",

            // Greetings
            "greeting.morning": "सुप्रभात",
            "greeting.afternoon": "नमस्ते",
            "greeting.evening": "शुभ संध्या",

            // Common
            "common.seeAll": "सभी देखें",
            "common.clear": "हटाएँ",
            "common.cancel": "रद्द करें",
            "common.save": "सेव करें",
            "common.close": "बंद करें",
            "common.done": "हो गया",
            "common.comingSoon": "जल्द आ रहा है",
            "common.open": "खोलें",
            "trust.footnote": "LexIndia एक कानूनी संदर्भ है, कानूनी सलाह नहीं।",
            "prepared.title": "तैयार हो रहा है",
            "guide.badge": "गाइड",

            // My Space
            "myspace.tagline": "आपकी रीडिंग, सेव किए सेक्शन, नोट्स और डाउनलोड।",
            "myspace.searchPlaceholder": "पूरे LexIndia में खोजें…",
            "myspace.membership": "सदस्यता",
            "myspace.quiz.title": "क्विज़ चैलेंज",
            "myspace.quiz.available": "साप्ताहिक इनाम उपलब्ध",
            "myspace.quiz.claimed": "स्टूडेंट्स कॉर्नर में खेलें",
            "myspace.studyTools": "स्टडी टूल्स",
            "myspace.categories": "कानूनी श्रेणियाँ",
            "myspace.categories.sub": "क्षेत्र के अनुसार कानून देखें",
            "myspace.browseCodes": "कोड ब्राउज़ करें",
            "myspace.allLaws": "सभी कानून",
            "myspace.continueReading": "जहाँ छोड़ा था वहीं से जारी रखें",
            "myspace.startClassic": "एक क्लासिक से शुरू करें",
            "myspace.situations": "आप किस स्थिति का सामना कर रहे हैं?",
            "myspace.topics": "प्रासंगिक विषय",
            "myspace.recents": "हाल में देखे गए",
            "myspace.saved": "सेव किए और नोट्स",
            "myspace.downloads": "मेरे डाउनलोड",
            "myspace.trial": "फ्री ट्रायल",
            "myspace.trial.endsIn": "समाप्त होगा",
            "myspace.seePlans": "प्लान देखें",
            "myspace.hint.saved": "पढ़ते समय सेक्शन बुकमार्क करें — वे आपके नोट्स के साथ यहाँ रहेंगे।",
            "myspace.hint.downloads": "कोर्ट फॉर्म, परीक्षा नोट्स और पेपर Documents से डाउनलोड किए जा सकते हैं।",

            // Library
            "library.title": "लॉ लाइब्रेरी",
            "library.subtitle": "कानून, स्टडी मटेरियल, अपडेट और दस्तावेज़",
            "library.lawsActs": "कानून और अधिनियम",
            "library.study": "स्टडी मटेरियल",
            "library.updates": "कानूनी अपडेट",
            "library.allUpdates": "सभी अपडेट",
            "library.documents": "दस्तावेज़",
            "library.documentsForms": "दस्तावेज़ और फॉर्म",
            "library.documents.sub": "बेयर एक्ट · कोर्ट फॉर्म · स्टडी PDF",
            "library.documents.foot": "बेयर एक्ट ऐप में पढ़ें · फॉर्म डाउनलोड और प्रिंट करें",
            "library.browseArea": "क्षेत्र के अनुसार देखें",
            "library.topics": "लोकप्रिय विषय",
            "library.ipc.sub": "पुरानी IPC धारा नए कोड में कहाँ है, जानें",
            "library.student.title": "स्टूडेंट्स कॉर्नर",
            "library.student.sub": "परीक्षा नोट्स · पिछले वर्षों के पेपर · रिवीज़न",
            "library.student.foot": "अपनी तैयारी के लिए डाउनलोड और प्रिंट करें",

            // Students Corner
            "students.title": "स्टूडेंट्स कॉर्नर",
            "students.subtitle": "लॉ छात्रों के लिए क्विज़, नोट्स, पेपर और टूल्स",
            "students.quizzes": "क्विज़",
            "students.quiz.sub": "खुद को परखें · साप्ताहिक क्रेडिट कमाएँ",
            "students.quiz.cta": "क्विज़ सेट करें",
            "students.resources": "स्टडी संसाधन",
            "students.tools": "स्टडी टूल्स",
            "students.coming": "स्टूडेंट्स कॉर्नर में जल्द",
            "students.courses": "कोर्सेज़",
            "students.courses.sub": "व्यवस्थित लर्निंग पाथ",
            "students.competitions": "प्रतियोगिताएँ",
            "students.competitions.sub": "निबंध और क्विज़ प्रतियोगिताएँ",
            "students.moot": "ऑनलाइन मूट कोर्ट",
            "students.moot.sub": "फोन से वकालत का अभ्यास करें",

            // Quiz
            "quiz.title": "क्विज़ चैलेंज",
            "quiz.subtitle": "विषय चुनें, लंबाई चुनें, शुरू करें",
            "quiz.topics": "विषय",
            "quiz.topics.hint": "एक या अधिक चुनें",
            "quiz.length": "प्रश्नों की संख्या",
            "quiz.available": "इस चयन में उपलब्ध",
            "quiz.start": "क्विज़ शुरू करें",
            "quiz.needTopics": "शुरू करने के लिए कम से कम एक विषय चुनें।",
            "quiz.pool.short": "इस लंबाई के लिए पर्याप्त प्रश्न नहीं — एक और विषय जोड़ें।",
            "quiz.weekly.available": "साप्ताहिक इनाम उपलब्ध",
            "quiz.weekly.claimed": "इस सप्ताह का इनाम मिल चुका — अगले सप्ताह फिर",
            "quiz.weekly.rule": "साप्ताहिक क्रेडिट इनाम के लिए लगातार पाँच क्विज़ में 100% स्कोर करें। इनाम सप्ताह में एक बार — क्विज़ हमेशा खेल सकते हैं।",
            "quiz.reward.per": "क्रेडिट",
            "quiz.question": "प्रश्न",
            "quiz.result.title": "आपका परिणाम",
            "quiz.result.pass": "शानदार!",
            "quiz.result.fail": "अभ्यास जारी रखें",
            "quiz.result.rewardAdded": "क्रेडिट आपके बैलेंस में जुड़ गए",
            "quiz.streak.title": "क्विज़ स्ट्रीक",
            "quiz.streak.progress": "%d / %d परफेक्ट स्कोर",
            "quiz.streak.one": "साप्ताहिक इनाम के लिए बस एक और 100% क्विज़।",
            "quiz.streak.need": "साप्ताहिक इनाम के लिए %d और 100% क्विज़ चाहिए।",
            "quiz.streak.reset": "100% से कम स्कोर पर स्ट्रीक फिर शुरू होती है — अभ्यास जारी रखें!",
            "quiz.streak.ready": "स्ट्रीक पूरी — इनाम पाने के लिए अगली क्विज़ पूरी करें।",
            "quiz.streak.complete": "स्ट्रीक पूरी! अगले सप्ताह की पहली क्विज़ पर इनाम मिलेगा।",
            "quiz.streak.afterClaim": "इनाम मिल गया — नई स्ट्रीक अभी से शुरू।",
            "quiz.streak.chip": "स्ट्रीक %d/%d",
            "quiz.result.timeUp": "समय समाप्त — क्विज़ अपने आप सबमिट हो गई।",
            "quiz.time.used": "लिया गया समय",
            "quiz.time.left": "बचा समय",
            "quiz.result.correct": "सही",
            "quiz.result.incorrect": "गलत",
            "quiz.result.unanswered": "बिना उत्तर",
            "quiz.result.questions": "प्रश्न",
            "quiz.result.perfect": "परफेक्ट स्कोर!",
            "quiz.review.title": "प्रश्न समीक्षा",
            "quiz.review.sub": "हर प्रश्न — आपका उत्तर और सही उत्तर।",
            "quiz.review.your": "आपका उत्तर",
            "quiz.review.correct": "सही उत्तर",
            "quiz.review.notAnswered": "उत्तर नहीं दिया",
            "quiz.playAgain": "फिर खेलें",
            "quiz.exit.title": "क्विज़ छोड़ें?",
            "quiz.exit.message": "इस क्विज़ की प्रगति खो जाएगी।",
            "quiz.exit.confirm": "छोड़ें",

            // E-Vakeel
            "evakeel.name": "ई-वकील",
            "evakeel.tagline": "आपका डिजिटल कानूनी सहायक",
            "evakeel.placeholder": "किसी कानून, प्रक्रिया या शब्द के बारे में पूछें…",
            "evakeel.disclaimer": "ई-वकील सामान्य कानूनी जानकारी देता है — यह योग्य वकील का विकल्प नहीं है।",
            "evakeel.empty.title": "नमस्ते 🙏",
            "evakeel.empty.message": "पूछें कोई कानून क्या कहता है, किसी प्रक्रिया में क्या होता है, या आप क्या कदम सोच सकते हैं।",
            "evakeel.try": "पूछ कर देखें",
            "evakeel.thinking": "ई-वकील सोच रहा है…",
            "evakeel.outOfCredits": "आपके क्रेडिट समाप्त हो गए हैं। लाइब्रेरी, खोज और नोट्स पूरी तरह उपलब्ध रहेंगे।",
            "evakeel.needMore": "इस प्रश्न के लिए आपके पास पर्याप्त क्रेडिट नहीं हैं।",
            "evakeel.manage": "अकाउंट में क्रेडिट प्रबंधित करें",
            "evakeel.advocate": "ऐसे मामले में किसी योग्य वकील से सलाह लेना उचित होगा — ई-वकील असली वकील का विकल्प नहीं है।",
            "evakeel.clear": "बातचीत साफ़ करें",
            "evakeel.creditUsed": "क्रेडिट उपयोग हुआ",
            "evakeel.creditsUsed": "क्रेडिट उपयोग हुए",
            "evakeel.noCharge": "इस प्रश्न के लिए कोई क्रेडिट नहीं लगा।",
            "evakeel.provision": "प्रासंगिक प्रावधान",
            "evakeel.openSection": "धारा खोलें",

            // Search
            "search.title": "LexIndia खोजें",
            "search.placeholder": "पूरे LexIndia में खोजें…",
            "search.recent": "हाल की खोजें",
            "search.popular": "लोकप्रिय खोजें",
            "search.noResults": "कोई परिणाम नहीं मिला",
            "search.noResults.sub": "धारा संख्या, कानूनी शब्द, अधिनियम, दस्तावेज़ या सेटिंग आज़माएँ।",
            "search.hint": "सब कुछ खोजें — कानून, धाराएँ, IPC नंबर, शब्द, केस, दस्तावेज़, नोट्स, अपडेट और सेटिंग्स।",
            "search.group.library": "लॉ लाइब्रेरी",
            "search.group.ipc": "IPC → BNS",
            "search.group.terms": "कानूनी शब्द",
            "search.group.cases": "केस लॉ",
            "search.group.documents": "दस्तावेज़",
            "search.group.students": "स्टूडेंट्स कॉर्नर",
            "search.group.updates": "कानूनी अपडेट",
            "search.group.myspace": "मेरा स्पेस",
            "search.group.settings": "सेटिंग्स",
            "search.linkedSections": "जुड़ी धाराएँ",

            // Account
            "account.title": "अकाउंट",
            "account.credits": "क्रेडिट",
            "account.credits.balance": "ई-वकील क्रेडिट",
            "account.credits.left": "शेष",
            "account.credits.history": "क्रेडिट इतिहास",
            "account.credits.note": "आपका क्रेडिट बैलेंस केवल यहीं दिखता है।",
            "account.yourLibrary": "आपकी लाइब्रेरी",
            "account.studyTools": "स्टडी टूल्स",
            "account.settings": "सेटिंग्स",
            "account.about": "जानकारी",
            "account.session": "सेशन",
            "account.saved": "सेव किए और नोट्स",
            "account.recents": "हाल में देखे गए",
            "account.downloads": "मेरे डाउनलोड",
            "account.definitions": "परिभाषाएँ",
            "account.caseLaws": "केस लॉ",
            "account.appearance": "थीम",
            "account.language": "भाषा",
            "account.appColor": "ऐप रंग",
            "account.privacy": "प्राइवेसी",
            "account.terms": "उपयोग की शर्तें",
            "account.disclaimer": "कानूनी अस्वीकरण",
            "account.signout": "साइन आउट",
            "account.membership": "सदस्यता",

            // Theme modes
            "theme.system": "स्वचालित",
            "theme.system.detail": "iPhone की थीम के अनुसार",
            "theme.light": "लाइट",
            "theme.light.detail": "हल्की पृष्ठभूमि, गहरा टेक्स्ट",
            "theme.dark": "डार्क",
            "theme.dark.detail": "गहरी बैंगनी पृष्ठभूमि, हल्का टेक्स्ट",
            "appearance.title": "थीम",
            "appearance.sub": "लाइट, डार्क, या iPhone जैसा",

            // App colour
            "appcolor.title": "ऐप रंग",
            "appcolor.sub": "एक रंग चुनें — बाकी LexIndia मिलाएगा",
            "appcolor.presets": "LexIndia पैलेट",
            "appcolor.custom": "कस्टम रंग",
            "appcolor.custom.pick": "कलर व्हील से कोई भी रंग चुनें",
            "appcolor.preview": "पूर्वावलोकन",
            "appcolor.reset": "LexIndia वायलेट पर रीसेट करें",
            "appcolor.note": "कोई भी रंग चुनें और पूरा ऐप उसी रंग के शेड्स में रँग जाता है — टाइलें, आइकन और बैज सहित। पृष्ठभूमि आपकी थीम के अनुसार लाइट या डार्क ही रहती है। LexIndia वायलेट सिग्नेचर रंगीन मिश्रण रखता है।",

            // Language screen
            "language.title": "भाषा",
            "language.sub": "अपनी LexIndia भाषा चुनें",
            "language.how": "भाषा कैसे काम करती है",
            "language.body1": "आपकी पसंद पूरे LexIndia इंटरफ़ेस पर लागू होती है — नेविगेशन, बटन, सेटिंग्स, खोज, स्टूडेंट्स कॉर्नर और संदेश — और लगातार बढ़ती रहेगी।",
            "language.body2": "आधिकारिक कानूनी पाठ हमेशा वैसा ही रहता है जैसा अधिनियमित हुआ — वह आपकी भाषा से कभी नहीं बदलता।",
            "language.more": "और भारतीय भाषाएँ जल्द आ रही हैं।",

            // Documents
            "docs.title": "दस्तावेज़",
            "docs.sub": "ज़रूरत के अनुसार व्यवस्थित",
            "docs.readInApp": "LexIndia में पढ़ें",
            "docs.downloadPdf": "PDF डाउनलोड करें",
            "docs.openPdf": "PDF खोलें",
            "docs.share": "शेयर करें",
            "docs.print": "प्रिंट करें",
            "docs.remove": "हटाएँ",
            "docs.saved": "आपके डिवाइस में सेव",
            "docs.links": "महत्वपूर्ण लिंक",
            "docs.links.sub": "आधिकारिक पोर्टल — ब्राउज़र में खुलेंगे",
            "docs.policy.bareActs": "बेयर एक्ट — ऐप में पढ़ें",
            "docs.policy.forms": "फॉर्म और नोट्स — PDF",
            "docs.readHere": "यहीं पढ़ें",

            // Reader & content
            "reader.section": "धारा",
            "reader.official": "आधिकारिक पाठ",
            "reader.simple": "सरल शब्दों में",
            "reader.understand": "और समझें",
            "reader.cases": "प्रमुख निर्णय",

            // Read aloud + translate
            "readaloud.listen": "सुनें",
            "readaloud.stop": "पढ़ना बंद करें",
            "translate.action": "हिन्दी में अनुवाद करें",

            // Updates
            "updates.title": "कानूनी अपडेट",
            "updates.sub": "अदालतें, नए कानून, संशोधन और अधिसूचनाएँ",
            "updates.cat.supreme-court": "सुप्रीम कोर्ट",
            "updates.cat.high-court": "हाईकोर्ट",
            "updates.cat.judgment": "निर्णय",
            "updates.cat.new-law": "नए कानून",
            "updates.cat.amendment": "संशोधन",
            "updates.cat.notification": "अधिसूचनाएँ",
            "updates.preview": "प्रीव्यू सामग्री। LexIndia यहाँ मूल संपादकीय सारांश प्रकाशित करेगा — स्रोत, समीक्षा, फिर प्रकाशन। डेमो प्रविष्टियाँ दिखाती हैं कि यह कैसा पढ़ेगा।",
            "updates.read": "सारांश पढ़ें",
            "updates.demo.note": "यह एक डेमो सारांश है, जब तक कानूनी अपडेट प्रीव्यू में है। असली अपडेट आधिकारिक स्रोतों या उचित लाइसेंस वाली सामग्री पर आधारित, संपादकीय समीक्षा से तैयार मूल LexIndia सारांश होंगे।",

            // Document kinds & detail
            "docs.kind.bare-act": "बेयर एक्ट्स",
            "docs.kind.bare-act.blurb": "आधिकारिक पाठ — LexIndia में पढ़ें",
            "docs.kind.court-form": "कोर्ट फॉर्म",
            "docs.kind.court-form.blurb": "व्यावहारिक प्रारूप — डाउनलोड और प्रिंट करें",
            "docs.kind.exam-note": "परीक्षा नोट्स",
            "docs.kind.exam-note.blurb": "परीक्षा तैयारी के लिए LexIndia नोट्स",
            "docs.kind.previous-paper": "पिछले वर्षों के पेपर",
            "docs.kind.previous-paper.blurb": "स्व-परीक्षण के लिए अभ्यास पेपर",
            "docs.kind.revision": "रिवीज़न मटेरियल",
            "docs.kind.revision.blurb": "अंतिम दोहराव के लिए संक्षिप्त चार्ट",
            "docs.badge.readInApp": "ऐप में पढ़ें",
            "docs.badge.downloaded": "डाउनलोड हो गया",
            "docs.bareact.note": "आधिकारिक बेयर एक्ट LexIndia लाइब्रेरी का हिस्सा हैं और ऐप के भीतर खुलते हैं — गाइड, IPC संदर्भ और केस के साथ। ये डिवाइस पर डाउनलोड नहीं होते।",
            "docs.download.note": "आपके डिवाइस पर प्रिंट-योग्य PDF सेव होता है — मेरे डाउनलोड से कभी भी खोलें, शेयर या प्रिंट करें, ऑफ़लाइन भी।",
            "docs.downloadedLine": "%@ को डाउनलोड · मेरे डाउनलोड में",
            "docs.link.indiacode": "केंद्रीय और राज्य अधिनियमों का आधिकारिक भंडार",
            "docs.link.ecourts": "केस स्थिति, कॉज़ लिस्ट और अदालती आदेश",
            "docs.link.sci": "निर्णय, कॉज़ लिस्ट और डिस्प्ले बोर्ड",
            "docs.link.efiling": "ज़िला अदालतों और हाईकोर्ट में ऑनलाइन केस दायर करें",

            // Library act tiles
            "library.badge.fulltext": "पूरा पाठ",
            "library.badge.ipcmap": "IPC मैप",
            "library.badge.guided": "गाइडेड",
            "library.badge.sections": "धाराएँ",
            "prepared.badge": "तैयारी में",
            "prepared.message": "इस अधिनियम का पूरा पाठ LexIndia के लिए तैयार किया जा रहा है। पूरी तरह गाइडेड धाराएँ लाइब्रेरी के अन्य अधिनियमों में उपलब्ध हैं।",

            // Act detail
            "act.contents": "विषय-सूची",
            "act.searchIn": "इस अधिनियम में खोजें",
            "act.ipcCard.title": "IPC से आ रहे हैं?",
            "act.ipcCard.sub": "पुराना IPC नंबर उसके BNS प्रावधान में बदलें",
            "act.beingPrepared": "तैयार हो रहा है",
            "act.source": "स्रोत",
            "act.notFound.title": "उपलब्ध नहीं",
            "act.notFound.act": "यह अधिनियम नहीं मिला।",
            "act.notFound.category": "यह श्रेणी नहीं मिली।",
            "act.noMatches": "कोई मेल नहीं",
            "act.noMatches.sub": "धारा संख्या या शीर्षक का कोई शब्द आज़माएँ।",
            "act.guidedSections": "गाइडेड धाराएँ",
            "chapter.foot.some": "%d धाराएँ · अब तक %d के लिए सरल-भाषा गाइड।",
            "chapter.foot.none": "%d धाराएँ · सरल-भाषा गाइड तैयार हो रही हैं।",
            "chapter.notFound": "यह अध्याय नहीं मिला।",

            // Reader extras
            "reader.chapter": "अध्याय",
            "reader.swipe": "धाराओं के बीच स्वाइप करें",
            "reader.sAbbrev": "धा.",
            "understand.example": "उदाहरण",
            "understand.keypoints": "मुख्य बिंदु",
            "understand.related": "संबंधित",
            "understand.definitions": "परिभाषाएँ",
            "understand.earlier": "पहले",
            "understand.oldcode": "पुराने कोड का संदर्भ",
            "understand.relatedSections": "संबंधित धाराएँ",
            "understand.casesOne": "इस धारा का 1 केस",
            "understand.casesMany": "इस धारा के %d केस",

            // My Space tools & membership
            "myspace.tool.defs": "कानूनी शब्द, सरल भाषा में",
            "myspace.tool.cases": "ऐतिहासिक निर्णय",
            "myspace.tool.ipc": "पुराने कोड से नए तक",
            "myspace.tool.study": "नोट्स · पेपर · रिवीज़न",
            "myspace.until": "%@ तक",
            "account.noPlan": "कोई प्लान नहीं",
            "account.devOnly": "केवल डेवलपमेंट",
            "account.testAccess": "टेस्ट एक्सेस",
            "plan.suffix": "प्लान",

            // Study material
            "study.sub": "लॉ छात्रों के लिए — डाउनलोड, प्रिंट, रिवाइज़ करें",
            "study.note": "नई सामग्री नियमित रूप से जुड़ती है। “डेमो” चिह्नित पेपर LexIndia अभ्यास सेट हैं, असली पुराने पेपर नहीं।",

            // Definitions
            "defs.sub": "कानूनी शब्दों को सरल भाषा में समझें",

            // IPC converter
            "ipc.note": "मैपिंग 2023 की संहिताओं की संगति तालिकाओं पर आधारित हैं। जहाँ प्रावधान बदला गया है, नोट यह बताता है — समतुल्यता का दावा नहीं है।",
            "ipc.open": "BNS धारा खोलें",
            "ipc.preparing": "गाइड तैयार हो रही है",
            "ipc.emptyTitle": "कोई मैपिंग नहीं मिली",
            "ipc.emptySub": "420, 302 या 498A जैसा IPC नंबर आज़माएँ।",
            "ipc.all": "सभी मैपिंग · IPC क्रम",
            "ipc.search": "IPC धारा खोजें, जैसे 420",
            "ipc.matches": "मेल",
            "defs.emptyTitle": "कोई मेल खाता शब्द नहीं",
            "defs.emptySub": "कोई दूसरा शब्द आज़माएँ — या पूरी शब्दावली देखें।",

            // Situations
            "situation.note": "ये प्रावधान आपको प्रासंगिक कानूनी जानकारी खोजने में मदद करते हैं। ये व्यक्तिगत कानूनी सलाह नहीं हैं।",
            "situation.provisions": "इस विषय से जुड़े LexIndia के प्रावधान",
            "situation.relevant": "प्रासंगिक प्रावधान",
            "situation.terms": "जानने योग्य शब्द",
            "situation.notFound": "यह स्थिति गाइड नहीं मिली।",
            "topic.notFound": "यह विषय नहीं मिला।",
            "defs.search": "शब्द खोजें",
            "defs.one": "परिभाषा",

            // Case laws
            "cases.sub": "वे निर्णय जिन्होंने कानून की समझ गढ़ी",
            "cases.note": "केस जानकारी संदर्भ के रूप में दी गई है। हमेशा आधिकारिक निर्णय से मिलान करें।",
            "cases.search": "केस लॉ में खोजें",
            "cases.emptyTitle": "कोई मेल खाता केस नहीं",
            "cases.emptySub": "पक्षकार का नाम या सिद्धांत का कोई शब्द आज़माएँ।",
            "cases.one": "केस लॉ",
            "cases.principle": "मुख्य सिद्धांत",
            "cases.summary": "सारांश",
            "cases.related": "संबंधित प्रावधान",
            "cases.notFound": "यह केस नहीं मिला।",

            // Quiz topics
            "quiz.topic.bns": "आपराधिक कानून — BNS",
            "quiz.topic.ipcBns": "IPC → BNS",
            "quiz.topic.bnss": "प्रक्रिया — BNSS",
            "quiz.topic.evidence": "साक्ष्य — BSA",
            "quiz.topic.constitution": "संवैधानिक कानून",
            "quiz.topic.contract": "संविदा अधिनियम",
            "quiz.topic.definitions": "कानूनी शब्द",
            "quiz.topic.cases": "प्रमुख निर्णय",

            // Credits
            "credits.explainer": "सरल प्रश्नों में 1 क्रेडिट लगता है; विस्तृत में अधिक। साप्ताहिक क्विज़ इनाम मुफ़्त क्रेडिट जोड़ते हैं।",
            "credits.low": "क्रेडिट कम हो रहे हैं — बिना रुकावट पूछते रहने के लिए टॉप-अप करें।",
            "credits.demo": "डेमो खरीद — इस प्रीव्यू बिल्ड में कोई भुगतान नहीं लिया जाता।",
            "credits.becomes": "आपका बैलेंस %d क्रेडिट हो जाएगा। इस प्रीव्यू में कोई भुगतान नहीं लिया जाता।",
            "credits.out": "आपके क्रेडिट समाप्त हो गए हैं। लाइब्रेरी, खोज और नोट्स पूरी तरह उपलब्ध रहेंगे — ई-वकील से पूछते रहने के लिए क्रेडिट जोड़ें।",
            "credits.summary": "बैलेंस %d · उपयोग %d · जुड़े %d",

            // Credits screens
            "credits.buyMore": "और क्रेडिट खरीदें",
            "credits.recent": "हाल की गतिविधि",
            "credits.demoTitle": "डेमो खरीद",
            "credits.addPack": "%d क्रेडिट जोड़ें — %@",
            "credits.remaining": "शेष",
            "credits.used": "उपयोग हुए",
            "credits.added": "जुड़े",
            "credits.pack.popular": "लोकप्रिय",
            "credits.pack.best": "सर्वोत्तम मूल्य",
            "credits.emptyTitle": "अभी कोई गतिविधि नहीं",
            "credits.emptySub": "क्रेडिट खरीद, ई-वकील उपयोग और क्विज़ इनाम यहाँ दिखेंगे।",

            // Notes & downloads
            "notes.add": "नोट जोड़ें…",
            "notes.savedOn": "%@ को सेव",
            "notes.emptyTitle": "अभी कोई सेव नोट नहीं",
            "notes.emptySub": "पढ़ते समय धाराएँ सेव करें — वे यहाँ दिखेंगी।",
            "notes.search": "अपने नोट्स में खोजें",
            "notes.your": "आपका नोट",
            "notes.saveNote": "नोट सेव करें",
            "common.delete": "हटाएँ",
            "downloads.browse": "दस्तावेज़ ब्राउज़ करें",
            "downloads.emptyTitle": "अभी कोई डाउनलोड नहीं",
            "downloads.emptySub": "कोर्ट फॉर्म, परीक्षा नोट्स, पेपर और रिवीज़न चार्ट प्रिंट-योग्य PDF के रूप में डिवाइस पर सेव किए जा सकते हैं।",
            "recents.emptySub": "आपकी पढ़ी धाराएँ यहाँ दिखेंगी, ताकि आप वहीं से आगे बढ़ सकें।",

            // Account extras
            "account.name.note": "आपके मेरा स्पेस अभिवादन में दिखता है।",
            "account.local.note": "आपके नोट्स, सेव किए सेक्शन और सदस्यता इसी डिवाइस पर रहते हैं।",
            "account.expiresLine": "%@ को समाप्त · %d ई-वकील क्रेडिट शामिल",
            "account.trial.line": "पूर्ण एक्सेस · %@ में समाप्त",
            "account.dev.note": "स्थायी डेवलपमेंट एक्सेस — असली प्लान नहीं। रिलीज़ से पहले हटा दिया जाएगा।",
            "account.plus.note": "पूरी कानूनी लाइब्रेरी, सरल-भाषा व्याख्याएँ, स्टडी टूल्स और ई-वकील क्रेडिट।",

            // Appearance body
            "appearance.body1": "स्वचालित आपके iPhone की लाइट/डार्क सेटिंग का अनुसरण करता है, ताकि LexIndia हमेशा घर जैसा लगे। हर समय एक ही रूप चाहें तो लाइट या डार्क चुनें।",
            "appearance.body2": "दोनों रूपों में टेक्स्ट और रंग मज़बूत कंट्रास्ट रखते हैं — हल्की पृष्ठभूमि पर गहरी स्याही, गहरी पर हल्की।",
            "appcolor.family": "आपके रंग का परिवार",
            "appearance.how": "थीम कैसे काम करती है",

            // Common extras
            "common.notNow": "अभी नहीं",
            "common.name": "नाम",
            "account.yourName": "आपका नाम",
            "account.signoutTitle": "साइन आउट करें?",
            "account.managePlan": "प्लान प्रबंधित करें",
            "common.all": "सभी",
            "updates.empty": "अभी यहाँ कुछ नहीं",
            "updates.empty.sub": "इस श्रेणी के अपडेट प्रकाशित होते ही दिखेंगे।",
            "updates.provisions": "प्रावधान पढ़ें",
            "updates.previewShort": "प्रीव्यू सामग्री",
            "updates.notFound": "यह अपडेट नहीं मिला।",
            "docs.notFound": "यह दस्तावेज़ नहीं मिला।",

            // Paywall
            "paywall.demo": "डेमो चेकआउट — इस प्रीव्यू बिल्ड में कोई भुगतान नहीं लिया जाता।",
            "paywall.includes": "%d ई-वकील क्रेडिट शामिल। इस प्रीव्यू में कोई भुगतान नहीं लिया जाता।",
            "paywall.hero": "पूरा भारतीय कानून,\nसरल शब्दों में।",
            "paywall.feature1": "हर गाइडेड अधिनियम, अध्याय और धारा",
            "paywall.feature2": "आधिकारिक पाठ, सरल-भाषा व्याख्याओं के साथ",
            "paywall.feature3": "IPC → BNS मैप, खोज, क्विज़ और ई-वकील",
            "paywall.try": "24 घंटे मुफ़्त आज़माएँ",
            "paywall.try.sub": "पूर्ण एक्सेस · कोई भुगतान नहीं · समाप्ति से पहले याद दिलाएँगे",
            "paywall.dev.note": "24-घंटे की सीमा के बिना ऐप देखने के लिए स्थायी टेस्ट एक्सेस। असली प्लान नहीं — यह विकल्प प्रोडक्शन से पहले हटा दिया जाएगा।",
            "paywall.dev.cta": "स्थायी टेस्ट एक्सेस खोलें",
            "paywall.signedIn": "%@ के रूप में साइन इन",
            "paywall.best": "सर्वोत्तम मूल्य",
            "paywall.save": "₹%d बचाएँ",
            "paywall.planLine": "%@ · %d ई-वकील क्रेडिट",
            "paywall.start": "शुरू करें %@ — %@",

            // Subscription sheet
            "sub.membership": "सदस्यता",
            "sub.title": "LexIndia Plus",
            "sub.tagline": "संपूर्ण कानूनी संदर्भ — बिना सीमा के भारतीय कानून पढ़ें, समझें और सीखें।",
            "sub.trial.active": "फ्री ट्रायल सक्रिय",
            "sub.trial.endsLine": "%@ में समाप्त। सब कुछ बनाए रखने के लिए प्लान चुनें।",
            "sub.dev.active": "स्थायी टेस्ट एक्सेस सक्रिय है। नीचे सब्सक्राइब करने पर यह असली प्लान से बदल जाएगा।",
            "sub.dev.end": "टेस्ट एक्सेस समाप्त करें",
            "sub.dev.endTitle": "टेस्ट एक्सेस समाप्त करें?",
            "sub.dev.endMessage": "आप सदस्यता स्क्रीन पर लौट जाएँगे।",
            "sub.dev.keep": "रखें",
            "sub.planActive": "%@ प्लान सक्रिय",
            "sub.planLine": "%@ · %d ई-वकील क्रेडिट शामिल",
            "sub.started": "प्रारंभ",
            "sub.expires": "समाप्ति",
            "sub.balance": "ई-वकील क्रेडिट बैलेंस",
            "sub.included": "शामिल",
            "sub.feat1": "पूरी कानूनी लाइब्रेरी — हर गाइडेड अधिनियम और धारा",
            "sub.feat2": "सरल-भाषा व्याख्याएँ और वास्तविक उदाहरण",
            "sub.feat3": "खोज, परिभाषाएँ, प्रमुख निर्णय और IPC → BNS",
            "sub.feat4": "नोट्स और सेव किए सेक्शन",
            "sub.feat5": "हर प्लान के साथ ई-वकील क्रेडिट",
            "sub.cancel": "सदस्यता रद्द करें",
            "sub.cancelTitle": "सदस्यता रद्द करें?",
            "sub.cancelMessage": "डेमो रद्दीकरण — इस प्रीव्यू में एक्सेस तुरंत समाप्त हो जाता है।",
            "sub.keepPlan": "मेरा प्लान रखें",

            // Auth
            "auth.tagline": "भारतीय कानून, सरल शब्दों में। धाराएँ पढ़ें, समझें और आत्मविश्वास से पढ़ाई करें।",
            "auth.preview.note": "प्रीव्यू साइन-इन — आपका खाता इसी डिवाइस पर रहता है। असली प्रमाणीकरण बैकएंड के साथ आएगा।",
            "auth.register": "खाता बनाएँ",
            "auth.signin": "साइन इन",
            "auth.toggle.toSignin": "पहले से खाता है? **साइन इन करें**",
            "auth.toggle.toRegister": "LexIndia पर नए हैं? **खाता बनाएँ**",
            "auth.email": "ईमेल पता",
            "auth.err.email": "कृपया मान्य ईमेल पता दर्ज करें।",
            "auth.err.name": "कृपया अपना नाम दर्ज करें।",
            "auth.err.notFound": "इस ईमेल से कोई खाता इस डिवाइस पर नहीं मिला। नया खाता बनाएँ।",

            // Trial & paywall extras
            "trial.keep": "हर धारा, व्याख्या और स्टडी टूल अपने पास रखें।",
            "trial.endsLine": "आपका मुफ़्त दिन %@ में समाप्त होगा। प्लान ₹128 से शुरू।",
            "paywall.choose": "अपना प्लान चुनें",
            "paywall.demoTitle": "डेमो चेकआउट",
            "sub.plans": "प्लान",
            "paywall.continue": "जारी रखें — %@ · %@",
            "paywall.expired.trial": "आपका मुफ़्त दिन समाप्त हो गया है। पढ़ते रहने के लिए प्लान चुनें — आपका सब सेव किया इंतज़ार में है।",
            "paywall.expired.plan": "आपका प्लान समाप्त हो गया है। पढ़ते रहने के लिए नवीनीकरण करें — आपका सब सेव किया इंतज़ार में है।"
        ]
    ]
}
